name: Fetch Weather
on:
  schedule:
    - cron: "0 4,10,14 * * *"
  workflow_dispatch:
jobs:
  get-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install node-fetch@2 firebase-admin
      - run: node fetchWeather.js
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS}}